# Generated by Django 5.2.8 on 2025-11-11 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lot_no", models.CharField(max_length=50, unique=True)),
                ("part_no", models.CharField(max_length=50)),
                ("customer", models.CharField(max_length=100)),
                ("po_no", models.CharField(blank=True, max_length=50, null=True)),
                ("quantity_target", models.IntegerField()),
                ("pcs_per_box", models.IntegerField()),
                ("department", models.CharField(max_length=100)),
                ("machine_no", models.CharField(max_length=50)),
                ("type", models.CharField(default="Order", max_length=50)),
                ("status", models.CharField(default="In Progress", max_length=50)),
                ("remark", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_no", models.CharField(max_length=50, unique=True)),
                ("machine_name", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ProductionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_datetime", models.DateTimeField(auto_now_add=True)),
                ("machine_no", models.CharField(max_length=50)),
                ("operator_name", models.CharField(max_length=100)),
                ("box_count", models.IntegerField(default=0)),
                ("pcs_count", models.IntegerField(default=0)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="production.lot"
                    ),
                ),
            ],
        ),
    ]
