# Generated by Django 5.2.8 on 2025-11-11 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_no", models.CharField(blank=True, max_length=50)),
                ("qty", models.IntegerField(default=0)),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Machine",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="pcs_per_box",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="po_no",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="quantity_target",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="remark",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="status",
        ),
        migrations.AddField(
            model_name="lot",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="lot",
            name="first_scan",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="lot",
            name="last_scan",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="lot",
            name="pieces_per_box",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lot",
            name="production_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lot",
            name="target",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lot",
            name="customer",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="lot",
            name="department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="lot",
            name="machine_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="lot",
            name="part_no",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="lot",
            name="type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="scanrecord",
            name="lot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="production.lot"
            ),
        ),
        migrations.DeleteModel(
            name="ProductionRecord",
        ),
    ]
