# Generated by Django 5.2.8 on 2025-11-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_no", models.CharField(max_length=50, unique=True)),
                ("machine_name", models.CharField(blank=True, max_length=100)),
                ("department", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="lot",
            name="customer_part_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lot",
            name="po_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lot",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
    ]
