# Generated by Django 5.2.8 on 2025-11-12 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "production",
            "0002_scanrecord_delete_machine_remove_lot_pcs_per_box_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="customer",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lot",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lot",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lot",
            name="first_scan",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lot",
            name="last_scan",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lot",
            name="machine_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="lot",
            name="part_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lot",
            name="type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="scanrecord",
            name="lot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scans",
                to="production.lot",
            ),
        ),
        migrations.AlterField(
            model_name="scanrecord",
            name="machine_no",
            field=models.CharField(max_length=50),
        ),
    ]
