# Generated by Django 5.2.8 on 2025-12-04 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0002_machine_lot_customer_part_no_lot_po_no_lot_remark"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="เวลาจบงาน (End)"
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="start_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="เวลาเริ่มงาน (Start)"
            ),
        ),
        migrations.CreateModel(
            name="DowntimeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="เวลาเริ่มหยุด")),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="เวลากลับมาทำต่อ"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="สาเหตุ"
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downtime_logs",
                        to="production.lot",
                    ),
                ),
            ],
        ),
    ]
