# Generated by Django 5.2.8 on 2025-12-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0003_lot_end_time_lot_start_time_downtimelog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lot",
            name="customer_part_no",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="first_scan",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="last_scan",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="pieces_per_box",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="po_no",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="production_quantity",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="remark",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="target",
        ),
        migrations.AddField(
            model_name="lot",
            name="operation_mode",
            field=models.CharField(
                choices=[("setup", "Setup"), ("production", "Production")],
                default="production",
                max_length=20,
                verbose_name="โหมดการทำงานปัจจุบัน (Setup/Production)",
            ),
        ),
    ]
