# Generated by Django 5.2.8 on 2025-11-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "production",
            "0004_department_alter_lot_description_alter_lot_lot_no_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanrecord",
            name="scanned_at",
            field=models.DateTimeField(),
        ),
    ]
