# Generated by Django 5.2.8 on 2025-12-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0004_remove_lot_customer_part_no_remove_lot_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="customer_part_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lot",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lot",
            name="first_scan",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lot",
            name="last_scan",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lot",
            name="pieces_per_box",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lot",
            name="po_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lot",
            name="production_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lot",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lot",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lot",
            name="target",
            field=models.IntegerField(default=0),
        ),
    ]
