# Generated by Django 5.2.8 on 2025-12-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "production",
            "0005_lot_customer_part_no_lot_end_time_lot_first_scan_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="run_mode",
            field=models.CharField(
                blank=True,
                choices=[("auto", "Auto"), ("manual", "Manual"), ("trial", "Trial")],
                help_text="เก็บโหมดที่เลือกจากหน้า Operator ตอนกด Start / Continue",
                max_length=20,
                null=True,
                verbose_name="โหมดเดินเครื่องล่าสุด (Auto/Manual/Trial)",
            ),
        ),
    ]
