# Generated by Django 5.2.8 on 2025-12-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0006_lot_run_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanrecord",
            name="sticker_unique_id",
            field=models.CharField(
                blank=True,
                help_text="เก็บเลข Unique ID จาก QR Code ป้องกันซ้ำ",
                max_length=50,
                null=True,
            ),
        ),
    ]
